### ISSUE TITLE
Failed to activate the parcel package

### ISSUE THREAD

**Issue by chrishough** [jamescmartinez/parcel#7]
### Stack Trace

Failed to activate the parcel package

```
At Script.createContext is not a function

TypeError: Script.createContext is not a function
    at Object.exports.eval (/packages/parcel/node_modules/coffee-script/lib/coffee-script/coffee-script.js:133:47)
    at parseObject (/packages/parcel/node_modules/season/lib/cson.js:144:34)
    at parseContentsSync (/packages/parcel/node_modules/season/lib/cson.js:155:14)
    at Object.readFileSync (/packages/parcel/node_modules/season/lib/cson.js:220:14)
    at PackageList.module.exports.PackageList.getPackages (/packages/parcel/lib/package-list.coffee:17:18)
    at PackageSync.module.exports.PackageSync.sync (/packages/parcel/lib/package-sync.coffee:41:20)
    at sync (/packages/parcel/lib/parcel.coffee:10:15)
    at Object.activate (/packages/parcel/lib/parcel.coffee:22:5)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:1)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:642:1)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:519:1
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:1)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:1)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:359:1
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:1)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
  2x -1:56.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -1:36.9.0 settings-view:open (input.hidden-input)
     -1:08.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.0.3 
atom-react-native-autocomplete 0.0.27 
auto-update-packages 1.0.1 
autocomplete-js-import 1.4.0 
autocomplete-ruby 0.2.8 
busy-signal 1.4.1 
emmet 2.4.3 
file-icons 2.1.6 
git-blame 1.0.2 
git-log 0.4.1 
git-plus 7.8.0 
glowing-cursor 0.1.2 
highlight-selected 0.13.1 
indent-guide-improved 1.4.12 
intentions 1.1.2 
language-babel 2.61.0 
language-haml 0.24.2 
language-javascript-jsx 0.3.7 
language-slim 0.5.0 
linter 2.1.4 
linter-eslint 8.1.7 
linter-rails-best-practices 0.2.2 
linter-rubocop 2.1.1 
linter-sass-lint 1.7.4 
linter-slim 1.0.0 
linter-ui-default 1.5.4 
markdown-scroll-sync 2.1.2 
maximize-panes 0.2.0 
move-panes 0.2.0 
package-sync 1.1.0 
parcel 0.1.0 
platformio-ide-terminal 2.5.0 
pretty-json 1.6.3 
react-es6-snippets 0.3.0 
react-snippets 0.7.2 
remote-sync 4.1.5 
set-syntax 0.3.2 
smart-tab-name 1.0.5 
tab-foldername-index 2.0.3 
tab-numbers 0.6.0 
tabularize 0.2.5 
trailing-spaces 0.4.0 
```

**Comment by jamescmartinez** [comment]
This package is no longer maintained. Sorry!

**Comment by chrishough** [comment]
😿
