### ISSUE TITLE
Uncaught TypeError: Script.createContext is not a function

### ISSUE THREAD

**Issue by tcn33** [jamescmartinez/parcel#8]
[Enter steps to reproduce:]

1. Packages > Parcel > Sync
2. Error is thrown

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [parcel](https://github.com/jamescmartinez/parcel) package 0.1.0

### Stack Trace

Uncaught TypeError: Script.createContext is not a function

```
At /Users/toby/.atom/packages/parcel/node_modules/coffee-script/lib/coffee-script/coffee-script.js:133

TypeError: Script.createContext is not a function
    at Object.exports.eval (/packages/parcel/node_modules/coffee-script/lib/coffee-script/coffee-script.js:133:47)
    at parseObject (/packages/parcel/node_modules/season/lib/cson.js:144:34)
    at parseContentsSync (/packages/parcel/node_modules/season/lib/cson.js:155:14)
    at Object.readFileSync (/packages/parcel/node_modules/season/lib/cson.js:220:14)
    at PackageList.module.exports.PackageList.getPackages (/packages/parcel/lib/package-list.coffee:17:18)
    at PackageSync.module.exports.PackageSync.sync (/packages/parcel/lib/package-sync.coffee:41:20)
    at sync (/packages/parcel/lib/parcel.coffee:10:15)
    at /packages/parcel/lib/parcel.coffee:20:7)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:08.0 parcel:sync (atom-pane.pane)
```

### Non-Core Packages

```
import-sf-mono 1.0.1 
language-javascript-jsx 0.3.7 
parcel 0.1.0 
```

**Comment by jamescmartinez** [comment]
This package is no longer supported. Sorry!

**Comment by JacopKane** [comment]
Having the same issue 😞 
It's sad; it was a good idea. Does anyone have better alternatives?
